<?php

namespace KimaiPlugin\GithubApiBundle\Controller;

use App\Configuration\SystemConfiguration;
use Github\Client;
use KimaiPlugin\GithubApiBundle\DependencyInjection\Configuration;

class GithubApiController extends Client
{
    public function __construct(SystemConfiguration $config)
    {
        parent::__construct(null, $config->find('github_api.api_version'), $config->find('github_api.base_url'));

        if (Configuration::AUTHENTICATION_DISABLED !== $config->find('github_api.authentication.type')) {
            $tokenOrLogin = null;
            $password = null;

            switch ($config->find('github_api.authentication.type')) {
                case Client::AUTH_HTTP_TOKEN:
                case Client::AUTH_URL_TOKEN:
                    $tokenOrLogin = $config->find('github_api.authentication.token');
                    break;
                case Client::AUTH_URL_CLIENT_ID:
                    $tokenOrLogin = $config->find('github_api.authentication.client_id');
                    $password = $config->find('github_api.authentication.client_secret');
                    break;
                case Client::AUTH_HTTP_PASSWORD:
                    $tokenOrLogin = $config->find('github_api.authentication.username');
                    $password = $config->find('github_api.authentication.password');
            }
            $this->authenticate($tokenOrLogin, $password, $config->find('github_api.authentication.type'));
        }
    }

    public function api($name)
    {
        return parent::api($name); // TODO: Change the autogenerated stub
    }
}